name: Basic Workflow
on: 
  workflow_dispatch:  # Allows manual triggering
  push:

jobs:
  k6_local_test:
    name: k6 local test run - basic example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: script.js
        
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      # - name: Upload to S3
      #   run: |
      #     aws s3 cp ./summary.html s3://${{ secrets.AWS_S3_BUCKET }}/k6-reports/${{ github.run_id }}/summary_$(date +%Y%m%d_%H%M%S).html
      - name: Upload to S3
        id: upload
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          aws s3 cp ./summary.html s3://k6-test-report/k6-reports/run_$(date +%Y%m%d_%H%M%S)/summary_$TIMESTAMP.html    
          REPORT_URL="https://k6-test-report.s3.ap-south-1.amazonaws.com/k6-reports/run_$TIMESTAMP/summary_$TIMESTAMP.html"

          # Display in workflow (3 ways)
          echo "::notice title=ðŸ“Š K6 Report Published::View report: $REPORT_URL"
          echo "REPORT_URL=$REPORT_URL" >> $GITHUB_OUTPUT
          echo "### ðŸ”— Performance Test Report" >> $GITHUB_STEP_SUMMARY
          echo "[Click to view full report]($REPORT_URL)" >> $GITHUB_STEP_SUMMARY
          echo "Direct URL: \`$REPORT_URL\`" >> $GITHUB_STEP_SUMMARY

        
          aws s3 cp ./summary.html s3://k6-test-report/k6-reports/run_$(date +%Y%m%d_%H%M%S)/summary_$(date +%Y%m%d_%H%M%S).html
          echo "Permanent URL: https://k6-test-report.s3.ap-south-1.amazonaws.com/k6-reports/run_$(date +%Y%m%d_%H%M%S)/summary_$(date +%Y%m%d_%H%M%S).html"


